name: CI

on:
  push:
    branches:
      - main

jobs:

  build-and-push:
    name: 'Checkout | generate SHA | Dockerhub Login | Build and Push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: 'Generate SHA'
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    - name: 'Dockerhub Login'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_SERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 'Build and Push'
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          herickdevelp/nlw-journey-devops:${{ steps.generate_sha.outputs.sha }}
          herickdevelp/nlw-journey-devops:latest