name: CI

on:
  push:
    branches:
      - main

jobs:

  login:
    name: 'Login'
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Dockerhub Login'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_SERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: 'Generate SHA'
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT
      

    - name: 'Build docker image'
      run: docker build -t herickdevelp/nlw-journey-devops:${{ steps.generate_sha.outputs.sha }} .